name: Supabase DB Connectivity Check

on:
  workflow_dispatch:

jobs:
  check-db:
    runs-on: ubuntu-latest

    steps:
      - name: Install PostgreSQL client
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      - name: Check pg_dump connectivity
        env:
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
        run: |
          echo "🔍 Testing pg_dump connectivity to Supabase..."
          pg_dump --schema-only "$SUPABASE_DB_URL" --no-owner --no-privileges --verbose -f /tmp/test_dump.sql
          echo "✅ pg_dump connection successful!"
